development:
  adapter: mysql2
  database: bug_tracker_development
  pool: 5
  timeout: 5000

test:
  adapter: mysql2
  database: bug_tracker_test
  pool: 5
  timeout: 5000

production:
  adapter: mysql2
  database: bug_tracker_production
  pool: 5
  timeout: 5000